### ISSUE TITLE
Is possible to compile in kernel 4.4.3 to support DSM 7.2

### ISSUE THREAD

**Issue by ikeooo** [mafredri/asustor-platform-driver#17]
Is possible to compile in kernel 4.4.3 to support DSM 7.2 for install DMS 7.2 in asustor model?

**Comment by ikeooo** [comment]
When i try it on DSM 7.2. it shows several error

**Comment by ikeooo** [comment]
/volume1/linux/asustor/asustor-platform-driver# make CROSS_COMPILE=/volume1/linux/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-
  CC [M]  /volume1/linux/asustor/asustor-platform-driver/asustor.o
/volume1/linux/asustor/asustor-platform-driver/asustor.c:37:18: error: ‘struct gpio_led’ has no member named ‘panic_indicator’
   37 |                 .panic_indicator = 1,
      |                  ^~~~~~~~~~~~~~~
/volume1/linux/asustor/asustor-platform-driver/asustor.c:37:36: warning: initialization of ‘struct gpio_desc *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   37 |                 .panic_indicator = 1,
      |                                    ^
/volume1/linux/asustor/asustor-platform-driver/asustor.c:37:36: note: (near initialization for ‘asustor_leds[3].gpiod’)
/volume1/linux/asustor/asustor-platform-driver/asustor.c: In function ‘asustor_init’:
/volume1/linux/asustor/asustor-platform-driver/asustor.c:324:34: error: ‘const struct gpiod_lookup’ has no member named ‘key’
  324 |                 for (; keys_table->key != NULL; keys_table++) {
      |                                  ^~
/volume1/linux/asustor/asustor-platform-driver/asustor.c:328:69: error: ‘const struct gpiod_lookup’ has no member named ‘key’
  328 |                                         find_chip_by_name(keys_table->key);
      |                                                                     ^~
make[2]: *** [scripts/Makefile.build:287: /volume1/linux/asustor/asustor-platform-driver/asustor.o] Error 1
make[1]: *** [Makefile:1467: _module_/volume1/linux/asustor/asustor-platform-driver] Error 2
make: *** [Makefile:24: modules] Error 2
root@ike-nas:/volume1/linux/asustor/asusto

**Comment by frankol** [comment]
same here. cant compile it. Even if i disable the warnings and let compile it, i cant use it in DSM since it throw the same errors in dmesg.

**Comment by mafredri** [comment]
Are you running DSM on ASUSTOR hardware, or trying use this project with Synology hardware? I ask because the latter doesn't really make sense for this driver.

Either way, I'm happy to accept PRs for this but not something I'm planning to work on myself as I don't have any way to test it.

**Comment by frankol** [comment]
Im running DSM on ASUSTOR hardware. For compile i have a ubuntu with [(https://help.synology.com/developer-guide/getting_started/prepare_environment.html)] prepared. Many modules i can compile without errors or warning, just this one makes me some trouble.
