### ISSUE TITLE
AS6602T error on make linux-headers-6.17.2-2-pve

### ISSUE THREAD

**Issue by sz3bbyla** [mafredri/asustor-platform-driver#40]
for kernel linux-headers-6.17.2-2-pve and kernel linux-headers-6.17.2-1-pve I have this error and I don't know to fix it

make[1]: Entering directory '/usr/src/linux-headers-6.17.2-2-pve'
make[2]: Entering directory '/root/asustor-platform-driver'
  CC [M]  asustor.o
  CC [M]  asustor_it87.o
  CC [M]  asustor_gpio_it87.o
asustor_gpio_it87.c:268:35: error: initialization of ‘int (*)(struct gpio_chip *, unsigned int,  int)’ from incompatible pointer type ‘void (*)(struct gpio_chip *, unsigned int,  int)’ [-Wincompatible-pointer-types]
  268 |         .set                    = it87_gpio_set,
      |                                   ^~~~~~~~~~~~~
asustor_gpio_it87.c:268:35: note: (near initialization for ‘it87_template_chip.set’)
make[4]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: asustor_gpio_it87.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:2016: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/root/asustor-platform-driver'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.17.2-2-pve'
make: *** [Makefile:24: modules] Error 2

**Comment by Terebi42** [comment]
We have a similar issue with 6.17.9  @ich777

The following workaround appears to work 

```
sed -i 's/^static void it87_gpio_set(/static int it87_gpio_set(/' asustor-platform-driver/asustor_gpio_it87.c

sed -i '/^static int it87_gpio_set(/,/^}/ {
  /^}/ i\    return 0;
}' asustor-platform-driver/asustor_gpio_it87.c
```

**Comment by DanielGibson** [comment]
~~try the latest code in main, it builds on my machine with kernel 6.17.5-arch1-1~~

nevermind, hat the wrong commit checked out
